### ISSUE TITLE
Impossile to change color of the blinking cursor

### ISSUE THREAD

**Issue by Johnrobmiller** [essserrr/crt-terminal#11]
When the styles to change the blinking cursor color are giving !important, the cursor stops blinking. If they are not given !important, the style is not applied.

**Comment by essserrr** [comment]
Hi.
Cursor can blink only because of the following animation:
```css
.characterSelected {
  color: $cursor-contrast-color;
  background-color: $cursor-color;
  animation: blink-character 1s steps(1, end) infinite;
}

@keyframes blink-character {
  50% {
    color: $cursor-color;
    background-color: transparent;
  }
}
```

If you want change cursor style, you should also change blinking animation itself

For css-modules it should look like (detailed path is provided for better understanding):

```css
.parent-container-style {
  :global
    .crt-terminal
    .crt-terminal__command-line
    .crt-command-line
    .crt-command-line__input-wrapper
    .crt-command-line__input-string
    .crt-cursor-symbol.crt-character {
      color: red;
      background-color: yellowgreen;

      & :local {
        animation: blink-character-custom 1s steps(1, end) infinite;
      }
  }

  @keyframes blink-character-custom {
    50% {
      color: yellowgreen;
      background-color: transparent;
    }
  }
}
```
